import tomllib
from pathlib import Path

import pytest
import vibesnake.qa.dependency_lock as dependency_lock

from vibesnake.qa.dependency_lock import (
    DependencyLockError,
    UV_VERSION,
    check_lock,
    compute_input_digest,
    validate_lock_text,
)


@pytest.mark.parametrize(
    ("profile", "minimum_packages"),
    [("ci", 1), ("runtime", 3)],
)
def test_repository_dependency_profiles_are_current(
    profile: str,
    minimum_packages: int,
) -> None:
    repository_root = Path(__file__).resolve().parents[2]

    assert check_lock(repository_root, profile) >= minimum_packages


def test_pytest_asyncio_configuration_has_an_explicit_locked_dependency() -> None:
    repository_root = Path(__file__).resolve().parents[2]
    project = tomllib.loads((repository_root / "pyproject.toml").read_text(encoding="utf-8"))
    pytest_options = project["tool"]["pytest"]["ini_options"]
    assert "asyncio_default_fixture_loop_scope" in pytest_options
    assert "asyncio_default_test_loop_scope" in pytest_options

    development_requirements = (repository_root / "requirements-dev.txt").read_text(encoding="utf-8")
    ci_lock = (repository_root / "requirements-ci.lock").read_text(encoding="utf-8")
    assert "pytest-asyncio>=1.4,<2\n" in development_requirements
    assert "pytest-asyncio==1.4.0 \\\n" in ci_lock


def test_input_digest_is_path_and_content_sensitive(tmp_path: Path) -> None:
    first = tmp_path / "requirements.txt"
    second = tmp_path / "requirements-dev.txt"
    first.write_text("runtime>=1\n", encoding="utf-8")
    second.write_text("-r requirements.txt\ntest>=2\n", encoding="utf-8")

    original = compute_input_digest(tmp_path, (first.name, second.name))
    second.write_text("-r requirements.txt\ntest>=3\n", encoding="utf-8")

    assert compute_input_digest(tmp_path, (first.name, second.name)) != original
    assert compute_input_digest(tmp_path, (second.name, first.name)) != original


def test_lock_validation_requires_current_inputs_pins_and_hashes(tmp_path: Path) -> None:
    (tmp_path / "requirements.txt").write_text("runtime>=1\n", encoding="utf-8")
    (tmp_path / "requirements-dev.txt").write_text(
        "-r requirements.txt\ntest>=2\n",
        encoding="utf-8",
    )
    digest = compute_input_digest(
        tmp_path,
        ("requirements.txt", "requirements-dev.txt"),
    )
    valid = (
        "# Generated by scripts/lock_python_dependencies.py.\n"
        "# Regenerate: python scripts/lock_python_dependencies.py --write\n"
        f"# Resolver: uv {UV_VERSION}\n"
        f"# Inputs-SHA256: {digest}\n"
        "runtime==1.2.3 \\\n"
        f"    --hash=sha256:{'a' * 64}\n"
        "test==2.4.0 ; python_version >= '3.11' \\\n"
        f"    --hash=sha256:{'b' * 64}\n"
    )

    assert (
        validate_lock_text(
            valid,
            tmp_path,
            ("requirements.txt", "requirements-dev.txt"),
        )
        == 2
    )

    with pytest.raises(DependencyLockError, match="stale"):
        validate_lock_text(
            valid.replace(digest, "0" * 64),
            tmp_path,
            ("requirements.txt", "requirements-dev.txt"),
        )
    with pytest.raises(DependencyLockError, match="exactly pinned"):
        validate_lock_text(
            valid.replace("runtime==1.2.3", "runtime>=1.2.3"),
            tmp_path,
            ("requirements.txt", "requirements-dev.txt"),
        )
    with pytest.raises(DependencyLockError, match="hash"):
        validate_lock_text(
            valid.replace(f"    --hash=sha256:{'a' * 64}\n", ""),
            tmp_path,
            ("requirements.txt", "requirements-dev.txt"),
        )


def test_cli_uses_the_explicit_checkout_root(tmp_path: Path, monkeypatch, capsys) -> None:
    observed: list[tuple[Path, str]] = []

    def fake_check_lock(repository_root: Path, profile_name: str) -> int:
        observed.append((repository_root, profile_name))
        return 7

    monkeypatch.setattr(dependency_lock, "check_lock", fake_check_lock)

    assert dependency_lock.main([], repository_root=tmp_path) == 0
    assert observed == [(tmp_path.resolve(), "ci")]
    assert capsys.readouterr().out == "Python ci dependency lock verified: packages=7\n"
