"""Generate and verify the hash-locked Python CI environment."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from typing import Sequence


UV_VERSION = "0.11.33"
LOCK_INPUTS = ("pyproject.toml", "requirements.txt", "requirements-dev.txt")
LOCK_NAME = "requirements-ci.lock"
_RUNTIME_LOCK_INPUTS = ("pyproject.toml", "requirements.txt", "requirements-runtime.txt")
_RUNTIME_LOCK_NAME = "requirements-runtime.lock"
_GENERATED_HEADER = (
    "# Generated by scripts/lock_python_dependencies.py.\n"
    "# Regenerate: python scripts/lock_python_dependencies.py --write\n"
    f"# Resolver: uv {UV_VERSION}\n"
)
_DIGEST_PATTERN = re.compile(r"^# Inputs-SHA256: ([a-f0-9]{64})$", re.MULTILINE)
_PIN_PATTERN = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^\s;\\]+)"
    r"(?:\s*;\s*[^\\]+)?\s*\\?$"
)
_HASH_PATTERN = re.compile(r"--hash=sha256:[a-f0-9]{64}(?:\s|$)")


class DependencyLockError(ValueError):
    """Raised when the CI dependency lock is missing, stale, or unsafe."""


@dataclass(frozen=True)
class _LockProfile:
    """One reproducible dependency graph and its resolver contract."""

    inputs: tuple[str, ...]
    lock_name: str
    source_requirement: str
    python_version: str
    regenerate_command: str

    @property
    def generated_header(self) -> str:
        return (
            "# Generated by scripts/lock_python_dependencies.py.\n"
            f"# Regenerate: {self.regenerate_command}\n"
            f"# Resolver: uv {UV_VERSION}\n"
        )


_LOCK_PROFILES = {
    "ci": _LockProfile(
        inputs=LOCK_INPUTS,
        lock_name=LOCK_NAME,
        source_requirement="requirements-dev.txt",
        python_version="3.11",
        regenerate_command="python scripts/lock_python_dependencies.py --write",
    ),
    "runtime": _LockProfile(
        inputs=_RUNTIME_LOCK_INPUTS,
        lock_name=_RUNTIME_LOCK_NAME,
        source_requirement="requirements-runtime.txt",
        python_version="3.11",
        regenerate_command=("python scripts/lock_python_dependencies.py --profile runtime --write"),
    ),
}


def compute_input_digest(repository_root: Path, inputs: Sequence[str] = LOCK_INPUTS) -> str:
    """Hash ordered requirement paths and exact bytes into one freshness identity."""
    repository_root = repository_root.resolve()
    digest = hashlib.sha256()
    for relative_path in inputs:
        path = (repository_root / relative_path).resolve()
        try:
            canonical_relative = path.relative_to(repository_root).as_posix()
        except ValueError as error:
            raise DependencyLockError(f"dependency input escapes the repository: {relative_path}") from error
        try:
            contents = path.read_bytes()
        except OSError as error:
            raise DependencyLockError(f"dependency input is unreadable: {canonical_relative}: {error}") from error
        digest.update(canonical_relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(contents)
        digest.update(b"\0")
    return digest.hexdigest()


def validate_lock_text(
    lock_text: str,
    repository_root: Path,
    inputs: Sequence[str] = LOCK_INPUTS,
    generated_header: str = _GENERATED_HEADER,
) -> int:
    """Require a current input digest and a SHA-256 hash on every exact pin."""
    if not lock_text.endswith("\n"):
        raise DependencyLockError("dependency lock must end with a newline")
    if not lock_text.startswith(generated_header):
        raise DependencyLockError("dependency lock has an unknown generator header")

    digest_match = _DIGEST_PATTERN.search(lock_text)
    expected_digest = compute_input_digest(repository_root, inputs)
    if digest_match is None or digest_match.group(1) != expected_digest:
        raise DependencyLockError("dependency lock is stale; regenerate it after changing requirement inputs")

    lines = lock_text.splitlines()
    requirement_indexes = [
        index for index, line in enumerate(lines) if line and not line[0].isspace() and not line.startswith("#")
    ]
    if not requirement_indexes:
        raise DependencyLockError("dependency lock contains no requirements")

    for position, start_index in enumerate(requirement_indexes):
        requirement_line = lines[start_index]
        if _PIN_PATTERN.fullmatch(requirement_line) is None:
            raise DependencyLockError(f"dependency must be exactly pinned: {requirement_line}")
        end_index = requirement_indexes[position + 1] if position + 1 < len(requirement_indexes) else len(lines)
        block = "\n".join(lines[start_index:end_index]) + "\n"
        if _HASH_PATTERN.search(block) is None:
            raise DependencyLockError(f"dependency pin has no SHA-256 hash: {requirement_line}")
    return len(requirement_indexes)


def _render_generated_lock(
    raw_lock: str,
    input_digest: str,
    generated_header: str = _GENERATED_HEADER,
) -> str:
    lines = raw_lock.splitlines()
    first_requirement = next(
        (index for index, line in enumerate(lines) if line and not line.startswith("#")),
        None,
    )
    if first_requirement is None:
        raise DependencyLockError("uv produced an empty dependency lock")
    payload = "\n".join(lines[first_requirement:]).rstrip() + "\n"
    return generated_header + f"# Inputs-SHA256: {input_digest}\n" + payload


def generate_lock(repository_root: Path, profile_name: str = "ci") -> int:
    """Resolve one profile's universal graph and replace its lock atomically."""
    repository_root = repository_root.resolve()
    profile = _LOCK_PROFILES[profile_name]
    uv_executable = shutil.which("uv")
    if uv_executable is None:
        raise DependencyLockError(f"uv {UV_VERSION} is required to regenerate the dependency lock")

    try:
        version_result = subprocess.run(
            [uv_executable, "--version"],
            cwd=repository_root,
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        raise DependencyLockError(f"unable to verify uv version: {error}") from error
    version_line = version_result.stdout.strip().splitlines()
    if not version_line or not re.match(
        rf"^uv {re.escape(UV_VERSION)}(?:\s|$)",
        version_line[0],
    ):
        actual_version = version_line[0] if version_line else "no version reported"
        raise DependencyLockError(f"uv {UV_VERSION} is required to regenerate locks; found {actual_version}")

    descriptor, generated_name = tempfile.mkstemp(prefix="vibesnake-requirements-", suffix=".lock")
    os.close(descriptor)
    generated_path = Path(generated_name)
    try:
        command = [
            uv_executable,
            "pip",
            "compile",
            profile.source_requirement,
            "--universal",
            "--python-version",
            profile.python_version,
            "--generate-hashes",
            "--output-file",
            str(generated_path),
        ]
        try:
            completed = subprocess.run(
                command,
                cwd=repository_root,
                check=True,
                capture_output=True,
                text=True,
                timeout=180,
            )
        except subprocess.CalledProcessError as error:
            details = (error.stderr or error.stdout or str(error)).strip()
            raise DependencyLockError(f"uv dependency resolution failed: {details}") from error
        except (OSError, subprocess.TimeoutExpired) as error:
            raise DependencyLockError(f"uv dependency resolution failed: {error}") from error

        if completed.stderr and "warning" in completed.stderr.lower():
            raise DependencyLockError(f"uv dependency resolution emitted a warning: {completed.stderr.strip()}")

        input_digest = compute_input_digest(repository_root, profile.inputs)
        try:
            raw_lock = generated_path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as error:
            raise DependencyLockError(f"generated dependency lock is unreadable: {error}") from error
        rendered = _render_generated_lock(
            raw_lock,
            input_digest,
            profile.generated_header,
        )
        count = validate_lock_text(
            rendered,
            repository_root,
            profile.inputs,
            profile.generated_header,
        )

        lock_path = repository_root / profile.lock_name
        descriptor, temporary_name = tempfile.mkstemp(
            dir=repository_root,
            prefix=f".{profile.lock_name}.",
            suffix=".tmp",
        )
        temporary_path = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
                stream.write(rendered)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary_path, lock_path)
        finally:
            temporary_path.unlink(missing_ok=True)
        return count
    finally:
        generated_path.unlink(missing_ok=True)


def check_lock(repository_root: Path, profile_name: str = "ci") -> int:
    """Validate the checked-in CI lock without contacting a package index."""
    profile = _LOCK_PROFILES[profile_name]
    lock_path = repository_root.resolve() / profile.lock_name
    try:
        lock_text = lock_path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise DependencyLockError(f"dependency lock is unreadable: {lock_path}: {error}") from error
    return validate_lock_text(
        lock_text,
        repository_root,
        profile.inputs,
        profile.generated_header,
    )


def main(
    argv: Sequence[str] | None = None,
    *,
    repository_root: Path | None = None,
) -> int:
    """Validate or write a lock for an explicitly selected checkout.

    The command-line wrapper supplies its own checkout root. Direct module
    execution uses the current directory instead of assuming that installed
    package files live inside a source checkout.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the universal hash lock with uv",
    )
    parser.add_argument(
        "--profile",
        choices=tuple(_LOCK_PROFILES),
        default="ci",
        help="dependency graph to verify or regenerate",
    )
    args = parser.parse_args(argv)
    root = (repository_root or Path.cwd()).resolve()
    try:
        count = generate_lock(root, args.profile) if args.write else check_lock(root, args.profile)
    except DependencyLockError as error:
        parser.error(str(error))
    action = "written" if args.write else "verified"
    print(f"Python {args.profile} dependency lock {action}: packages={count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
